import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils"
import Sidebar from "@/components/sidebar";
import { auth } from "@/auth";
import { fontPoppins, fontSans } from "./assets/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen font-sans",
          fontSans.variable,
          fontPoppins.variable
        )}>
            <div className="w-full h-full">
              {children}
            </div>
        </body>
    </html>

  );
}
