import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import Sidebar from "@/components/sidebar";
import { auth } from "@/auth";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <div className='flex pr-5 pb-5'>
      <div className="w-[20%] h-[95vh]">
        <Sidebar/>
      </div>
      <div className="w-full">
        {children}
      </div>
    </div>  
  );
}
